# Generated by Django 5.0.4 on 2024-09-13 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField()),
                ('permite_recorrencia', models.BooleanField(default=False)),
                ('quantidade_recorrencia', models.IntegerField(blank=True, null=True)),
                ('intervalo_recorrencia', models.IntegerField(blank=True, null=True)),
                ('status_recorrencia', models.CharField(blank=True, max_length=50, null=True)),
                ('agencia', models.IntegerField()),
                ('conta', models.IntegerField()),
                ('valor_pagamento', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
